title: Irfan Muzafar
logo: 
description: I am strong in explaining technical concepts in an easy to understand manner, through my experience as a Math tutor. With a passion for learning new skills, I have decided to enrol into a Data Science Immersive bootcamp by General Assembly. Being an Applied Math major, I was able to apply my analytical and problem solving skills to my Data Science projects. With this newfound passion, I look forward to showcase my adaptability to future data-related roles.
show_downloads: true
theme: jekyll-theme-minimal
