title: Irfan Muzafar
logo: 
description: Through my experience as a Secondary Math teacher in Geniebook, I was able to explain technical concepts in an easy to understand manner to help students accelerate their learning. With a passion for learning new skills, I have decided to enrol into a Data Science course by General Assembly. Being an Applied Math major, I was able to apply my analytical and problem solving skills to my Data Science projects. With this newfound passion, I look forward to show my adaptability to future data-related roles.
show_downloads: true
theme: jekyll-theme-minimal
