title: Irfan Muzafar
logo: 
description: Data Scientist with experience working as a Math Tutor. I studied Applied Mathematics at NTU, and went through Data Science Immersive at General Assembly Singapore. I did programming with Python for 5 years and enjoy presenting data visualisations to address problems.

I'm interested in the application of data science/analysis in any field.
show_downloads: true
theme: jekyll-theme-minimal
